#!/bin/bash

# رنگ سبز برای نام
green='\033[0;32m'
nc='\033[0m' # بدون رنگ

# نمایش نام شما به رنگ سبز
echo -e "${green}@KJx1111${nc}"

# رنج‌های آی‌پی تعریف شده
ranges=(
    "37.72.0."
    "37.97.124."
    "37.98.200."
    "45.80.85."
    "85.217.132."
)

# تعداد آی‌پی‌ها برای هر دسته
ip_count=10

# چاپ آی‌پی‌های IPv4:1
echo "IPv4:1:"
for ((i=0; i<$ip_count; i++)); do
  echo "${ranges[0]}$((i+1))"
done

# چاپ آی‌پی‌های IPv4:2
echo ""
echo "IPv4:2:"
for ((i=0; i<$ip_count; i++)); do
  echo "${ranges[1]}$((i+1))"
done
